POST http://localhost:3001/api/patients 
Content-Type: application/json

{
  "name":"hi",
  "dateOfBirth":"2000-06-14",
  "gender":"other",
  "occupation":"jobless",
  "ssn":"ssn",
  "random":"random"
}

### new entry
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date":"2020-01-01",
  "specialist":"Tein itse",
  "description": "Varvas ommeltu takaisin kiinni",
  "healthCheckRating": "0"
}