//GET PERSONS
GET http://localhost:3001/api/persons

###

//GET PERSON
GET http://localhost:3001/api/persons/1

###

//GET PERSON FAIL
GET http://localhost:3001/api/persons/0

###

//DELETE PERSON
DELETE http://localhost:3001/api/persons/1

###

//POST PERSON
POST http://localhost:3001/api/persons
Content-Type: application/json

    {
        "name":"Arto Hellas",
        "number": "040-123456",
        "id": 1
    }