//GET PERSONS
GET http://localhost:3001/api/persons

###

//GET PERSON
GET http://localhost:3001/api/persons/1

###

//GET PERSON FAIL
GET http://localhost:3001/api/persons/0

###

//DELETE PERSON
DELETE http://localhost:3001/api/persons/0

###

//POST PERSON
POST http://localhost:3001/api/persons
Content-Type: application/json

    {
        "name":"abc",
        "number": "040-123456"
    }