###//GET ALL
GET http://localhost:3003/api/users

###//POST
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username" : "nic",
  "name": "me",
  "password": "nic"
}

###//DELETE
DELETE http://localhost:3003/api/users/5ec3e7bd27fd011a6ca58529